version: "3.8"
services:
  env:
    build:
      context: "./.docker"
      dockerfile: "Dockerfile"
    command: "tail -f /dev/null"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
